### ISSUE TITLE
Autonomous exploration

### ISSUE THREAD

**Issue by joyde3382** [jackal/jackal_cartographer_navigation#1]
Got the simulation up and running and I am able make the simulated robot move around in Rviz while mapping the area. However i am wondering if you can make it move around by itself, exploring the area, while seeking undiscovered areas?

Thanks in advance

**Comment by tonybaltovski** [comment]
Hello!

Great questions! Unfortunately this isn't quite the correct place for it, that's not something that we can inherently support. Your best bet would be to ask the ROS answers community, (https://answers.ros.org/questions/) there's usually plenty of ROS experts there that will be willing to help.

Best of luck!
